OHDSI/PatientLevelPrediction

- DESCRIPTION
- README.md
- vignettes/BuildingPredictiveModels.Rmd
Here are some minor fixes to the package. It is better to have FeatureExtraction in the Depends section, so people don't have to type `FeatureExtraction::createCovariateSettings` but rather just `createCovariateSettings`.
> Some minor fixes

- inst/sql/sql_server/CreateCohorts.sql
> PLP execution fails

- R/AdaBoost.R
- inst/python/adaBoost.py
- inst/python/decisionTree.py
- inst/python/finalRandomForest.py
- inst/python/mlp.py
- inst/python/naive_bayes.py
- inst/python/python_predict.py
These changes allow the PLP python models to run on Linux/UNIX systems as well as Windows systems.
> Unix Compatibility

- R/Predict.R
- inst/python/python_predict.py
fix a bug in deep learning torch.
> fix bugs in deeplearningTorch

- R/Ensemble.R
Fix a small bug in ensembleTraining.
> fix a small bug in ensemble training

- inst/python/TorchUtils.py
remove unnecessary "import _cPcikle"
> remove unnecessary cPickle import.

- R/CIReNN.R
- man/setCIReNN.Rd
Signed-off-by: Seng Chan You <applegna@gmail.com>
> support multilayer CIReNN

- vignettes/PatientLevelPrediction.rmd
Making some updates to the install guide per my experience detailed in #128. I did not run pkgdown as part of this as I was unsure if all of those files were needed for the pull request review.
> Edits to quick install guide

- R/CIReNN.R
- R/EvaluatePlp.R
- R/Predict.R
- man/setCIReNN.Rd
Adding Bayes Drop-out layer to CIReNN
Adding GPU module for RNN for speed-up.
> Adding Bayes Drop-out layer to CIReNN and Adding GPU module for RNN

- R/HelperFunctions.R
I was getting an error when there is no existing virtual environment, and this fixes it.
> Avoid error caused by empty list

- R/HelperFunctions.R
Addressing OHDSI/PatientLevelPrediction/issues/#204.
> Bug fix: account for difference in `conda_*` and `virtualenv_*` functions

- .github/workflows/R_CMD_check_Hades.yaml
- DESCRIPTION
> testing check fix

- tests/testthat/helper-objects.R
- tests/testthat/test-andromedahelperfunctions.R
- tests/testthat/test-evaluation.R
- tests/testthat/test-population.R
Hi, 
I added some test codes for unit-test. 
1. batchRestrict 
2. modelBasedConcordance
3. stdca
in the case of stdca, I added test code for evaluatePlp.R using Cox survival model.
If not appropriate or available, please close this PR. 
Chungsoo
> add unit tests

- R/Simulation.R
adding defaultCovariateSetting list to simulation data for unit test
> add CovariateSettings to simulation data

- R/Recalibration.R
@jreps This should resolve the issue when recalibrating with multiple methods.
> Resolve an issue with missing meta data

- R/Sampling.R
@jreps testing pull request with a minor edit
> Multiplication gives inverse

- R/CyclopsModels.R
- R/CyclopsSettings.R
Cyclops allows us to provide starting coefficients to a logistic regression model. This parameter is passed through to the logistic regression model settings of PLP.
> Provide starting coefficients as parameter to logistic regression models

- R/Sampling.R
- R/uploadToDatabase.R
- tests/testthat/test-sampling.R
- added tests to check sample data returns plpData
- fixed output of over sample
- added plpData class to over and under sample
> fixing issue #286

- DESCRIPTION
- NEWS.md
- R/AndromedaHelperFunctions.R
- R/CovariateSummary.R
- R/CyclopsModels.R
- R/DemographicSummary.R
- R/DiagnosePlp.R
- R/ExternalValidatePlp.R
- R/FeatureImportance.R
- R/Formatting.R
- R/GradientBoostingMachine.R
- R/ImportFromCsv.R
- R/LearningCurve.R
- R/Plotting.R
- R/PopulationSettings.R
- R/Predict.R
- R/Recalibration.R
- R/RunMultiplePlp.R
- R/RunPlp.R
- R/SklearnClassifier.R
- tests/testthat/test-covariateExtras.R
- tests/testthat/test-featureEngineering.R
- tests/testthat/test-featureImportance.R
- tests/testthat/test-formatting.R
- tests/testthat/test-prediction.R
- tests/testthat/test-recalibration.R
- vignettes/AddingCustomModels.Rmd
- removing check warnings
- fixing occasional test failed
> test and check clean

- R/Formatting.R
- tests/testthat/test-formatting.R
- No longer checks free ram to make sure you have enough
- Now a message with estimated RAM requirements is printed
> removing ram stop

- R/Fit.R
- R/KNN.R
- R/RClassifier.R
- R/Recalibration.R
- R/RunPlp.R
- man/fitPlp.Rd
- tests/testthat/test-KNN.R
- tests/testthat/test-LightGBM.R
- tests/testthat/test-cyclopsModels.R
- tests/testthat/test-fitting.R
- tests/testthat/test-rclassifier.R
- tests/testthat/test-sklearnClassifier.R
Resolves issue https://github.com/OHDSI/PatientLevelPrediction/issues/381
> Pass analysis path to fit function

- R/HelperFunctions.R
- R/SklearnToJson.R
> wrap comparisons with python objects in py_bool

- DESCRIPTION
> remove unnecessary remotes

- R/GradientBoostingMachine.R
- tests/testthat/helper-functions.R
- tests/testthat/test-rclassifier.R
> Informative error message when no outcomes in early stopping set xgboost

- R/ExternalValidatePlp.R
> Add cache for validate external

- DESCRIPTION
> remove FE remote

- README.md
> remove python3.8 from readme

- tests/testthat/test-UploadToDatabase.R
> 405 no ci in fork

- R/uploadToDatabase.R
- tests/testthat/test-UploadToDatabase.R
> also delete migration tables if deleting

- R/AdditionalCovariates.R
- tests/testthat/test-covariateExtras.R
> startDay and endDay in analysisRef for cohortCovs + test

- DESCRIPTION
- NEWS.md
- R/ExtractData.R
- tests/testthat/test-extractData.R
> fix restrictPlpDataSettings check in getPlpData

- R/FeatureEngineering.R
- R/SklearnClassifierSettings.R
- R/SklearnToJson.R
- tests/testthat/test-LightGBM.R
- tests/testthat/test-UploadToDatabase.R
- tests/testthat/test-cyclopsModels.R
- tests/testthat/test-existingModel.R
- tests/testthat/test-featureEngineering.R
- tests/testthat/test-learningCurves.R
- tests/testthat/test-multiplePlp.R
- tests/testthat/test-plotting.R
- tests/testthat/test-rclassifier.R
- tests/testthat/test-sklearnClassifier.R
- tests/testthat/test-sklearnClassifierSettings.R
- tests/testthat/test-sklearnJson.R
> adjust conditional tests and examples

- .Rbuildignore
- .github/workflows/release_docker.yaml
- .gitignore
- Dockerfile
- tests/testthat/test-evaluation.R
- tests/testthat/test-featureEngineering.R
Add dockerfile and github actions to build docker and release to dockerhub when a new release is tagged.
> 560 docker

- R/RClassifier.R
- R/SklearnClassifier.R
- tests/testthat/helper-expectations.R
- tests/testthat/setup.R
- tests/testthat/test-rclassifier.R
- tests/testthat/test-sklearnClassifier.R
> fix one feature bug and test
