R/CIReNN.R, man/setCIReNN.Rd
Hello,
To let users set arguments for early stopping in CIReNN, I added params for earlyStopping in set function.
And to save memory, I modify the fitCIReNN to remove result(sparse array for whole feature vector) among the code.
=> Adding params for earlyStopping arguments

R/RunMultiplePlp.R, man/runPlpAnalyses.Rd
Hi,
can we add a flag to only fetch plpData when using a prediction package without running the analyses? Currently `runPlpAnalyses()` always does both at the same time ;-)
Use case 1: Allows us to split up larger studies into "data fetching" and "model fitting".
Use case 2: Allows us to use ATLAS prediction packages to fetch data on machine 1, but run analysis on machine 2.
Let me know, if this functionality already exists when using the prediction packages and I have just overlooked it. Otherwise, I propose something as in the commit attached; the flag will need to be passed through to the `execute()` function in `Main.R` of the prediction packages. I am happy to provide a pull request for that as well with some additional checks (e.g. creating a shiny should not be possible when only …
=> Add flag to only fetch data without running analyses

DESCRIPTION, R/LearningCurve.R, R/Plotting.R, man/plotLearningCurve.Rd
Some minor improvements to the existing learning curve code base:
- The plotting function now uses conventions and terminology as used in our learning curve publication.
- The learning curve object has been extended by a column to now also return the number of predictors (`nPredictors`) for each data point.
@jreps I have been a bit confused by the implementation of the melted learning curve data frame, which is then pivoted. Therefore, I added the new column `nPredictors` at the end of the code, when the data frame row was already pivoted and is about to be returned. It is working fine now, but if you manage to add the `nPredictors` column before pivoting, that would make it more consistent.
(To avoid confusion, this pull request does not fix the call to `utils::memory.size()`, which …
=> Learning curve improvements

R/DataSplitting.R, tests/testthat/test-dataSplitting.R
There was an issue with the subjectSplitter function. 
It uses the R function round() to get indices for the train and test set. But when the expression inside the round ends in a .5 this function rounds to the nearest even number. For example if it was 20.5 the rounding would result in 20. So the test set would for example go from 1:20. But then for the training set we add 1 to the index, so it's 21.5 and then the rounding gives 22. So the training set is from 22 and upwards. So subject 21 is left out.  
I first added a test to test this situation and indeed it failed with the current code. Then I modified the code so it always rounds up when the expression ends in .5. Then the test passed.
I ran the tests for all the data-splitting functions and they all pass. But I'm struggling to run …
=> fixed subjectSplitter and added test for subjects unassigned to folds

R/DataSplitting.R
An error occurred in this step of the dataSummary function (in DataSplitting.R) as below. 
```r
result <- data$Train$labels %>% 
dplyr::inner_join(data$Train$folds, by = .data$rowId) %>% 
dplyr::group_by(.data$index) %>%
dplyr::summarise(N = length(.data$outcomeCount),
outcomes = sum(.data$outcomeCount)) %>% 
dplyr::collect()
```
After I picked the column directly as 'by = 'rowId' ' than 'by = .data$rowId', the error resolved.
```r
result <- data$Train$labels %>% 
dplyr::inner_join(data$Train$folds, by = 'rowId') %>% 
dplyr::group_by(.data$index) %>%
dplyr::summarise(N = length(.data$outcomeCount),
outcomes = sum(.data$outcomeCount)) %>% 
dplyr::collect()
```
=> [issue242] fix .data related error

DESCRIPTION, R/Plotting.R, man/plotSmoothCalibration.Rd, tests/testthat/test-plotting_updated.R
Fixing issues with `plotSmoothCalibration` function:
- Fix restricted cubic spline plotting
- Attempt to modularize with the addition of `plotSmoothCalibrationLoess` and `plotSmoothCalibrationRcs` functions
- Remove zoom option and always plot using limits (0, 1)
- Return a list of `ggplot` plots per evaluation type that can be further manipulated (theming etc)
- `$smoothPlot` the plot with the smooth calibration
- `$histPlot` the plot with the outcome count histograms
- Update the tests (they should not be failing now)
=> Smooth calibration

R/Simulation.R
Fixes a small bug in simulatePlpData. The covariateData object wouldn't print correctly unless it has a cohortId in it's metaData attribute.
=> add cohortId to covariateData metaData

.Rbuildignore, DESCRIPTION, NEWS.md, R/ExtractData.R, R/SaveLoadPlp.R, R/SklearnClassifierSettings.R, R/uploadToDatabase.R, R/uploadToDatabaseDiagnostics.R, R/uploadToDatabaseModelDesign.R, R/uploadToDatabasePerformance.R, man/createDatabaseSchemaSettings.Rd, man/createPlpResultTables.Rd, man/extractDatabaseToCsv.Rd, man/outcomeSurvivalPlot.Rd, tests/testthat/test-UploadToDatabase.R, tests/testthat/test-rclassifier.R
- renamed the input corresponding to the string that gets appended to the results table names to tablePrefix
- fixed issues with system.file() from SqlRender code breaking the tests
- added an input fileAppend to the function that exports the database tables to csv files
- moved the plp model (including preprocessing details) outside of the result database (into a specified folder) due to the size of the objects (too large to insert into the database).
=> bug fixes and minor updates

.github/workflows/R_CMD_check_Hades.yaml, R/CyclopsModels.R, R/CyclopsSettings.R, R/EvaluationSummary.R, R/ExternalValidatePlp.R, R/FeatureEngineering.R, R/KNN.R, R/PreprocessingData.R, R/SaveLoadPlp.R, R/Simulation.R, R/ThresholdSummary.R, R/uploadToDatabase.R, man/setLassoLogisticRegression.Rd, tests/testthat/helper-objects.R, tests/testthat/test-KNN.R, tests/testthat/test-UploadToDatabase.R, tests/testthat/test-andromedahelperfunctions.R, tests/testthat/test-featureImportance.R, tests/testthat/test-sklearnClassifier.R, tests/testthat/test-validation.R
Here is the PR I mentioned yesterday for you to review @jreps . 
Features
- Changed cyclops coefficient to use a data.frame with columns ```betas``` and ```covariateIds``` instead of a named vector. 
- Adapted test for external validation to follow real world behavior, almost always you load the model from disk and then validate externally. This would have caught the json saving bug. 
- Added ```quiet=True``` to all AUC calculations, silencing the message that comes everytime you calculate the AUC.
Bugfixes
- Added priorCoefs to documentation since it was failing the R CMD check. 
- Fixed a small bug where the externalValidate wasn't picking up the population settings which caused a test failure 
- There was a hardcoded ```.json``` in the sklearn test, now since that has been turned of it …
=> Load json cyclops fix - faster tests - fixes of various test failures

DESCRIPTION, R/CyclopsSettings.R
@jreps  I removed the survAUC dependancy which wasn't used anymore. This finally gets rid of Hmisc  and rms so @rekkasa work pays off in reduced dependencies for PLP.
=> remove survAUC

DESCRIPTION, NEWS.md, R/CyclopsModels.R
- Adds priorType to getCV in CyclopsModels.R . It was hardcoded as 'laplace' but for different models such as ridge or IHT that won't work. Now it gets the priorType from the modelSettings
- Fix a small bug with the seed given to Cyclops models. It wasn't actually passed to cyclops but should be now
- Updated news with these changes and updated version to 6.0.5
All test passed locally.
=> pass seed to cyclops and add priorType to getCV

R/FeatureEngineering.R
fixes 2 out of 3 failing tests reported in #343 
The cause was a new scikit-learn version adding a check for an input that should be an integer, but in older versions didn't check and worked both with numerics and integers.
I've not so far been able to reproduce the last failing test.
@jreps can you review and merge this?
=> Univariate fix

R/GradientBoostingMachine.R, R/SklearnClassifier.R, R/SklearnClassifierSettings.R, man/setDecisionTree.Rd, man/setMLP.Rd, man/setRandomForest.Rd, man/setSVM.Rd, tests/testthat/helper-expectations.R, tests/testthat/helper-functions.R, tests/testthat/helper-objects.R, tests/testthat/test-KNN.R, tests/testthat/test-cyclopsModels.R, tests/testthat/test-featureEngineering.R, tests/testthat/test-featureImportance.R, tests/testthat/test-fitting.R, tests/testthat/test-learningCurves.R, tests/testthat/test-preprocessingData.R, tests/testthat/test-rclassifier.R, tests/testthat/test-sampling.R, tests/testthat/test-sklearnClassifier.R, tests/testthat/test-sklearnClassifierSettings.R
fixes #350 
Also changed a few things with sklearn models: 
- Removed 'balanced' option from default set of hyperparameters from various models. Various models used these to put more weight on the minority class when optimizing. In light of @cynthiayang525 work on class imbalance I think its reasonable to not include those in the defaults. This reduces the search space by a factor of 2x. For example random forest goes from about 200 runs to 100 for the default set. 
- Changed ```epsilon``` in the sklearn MLP to one value in the defaults. This is a parameter for numerical stability during optimization and doesn't make sense to include it in hyperparameter tuning (or even changing it really). This reduces the search space by a factor of 3x for the MLP.
I updated the tests:
- create …
=> Scikit learn fixes

R/ImportFromCsv.R, R/uploadToDatabase.R, tests/testthat/test-UploadToDatabase.R
This PR solves an issue related to the upcoming DatabaseConnector 6.0.0: The getTableNames funtion will be changed to output in lowercase instead of uppercase for greater consistency across HADES (and to support dbplyr). Some code in PLP expects the output to be in uppercase. I've now made the checks case-insensitive, so it works both with the old and new versions of DatabaseConnector.
Note that I've based this PR on the main branch instead of develop. I was hoping this could be incorporated in a patch release, so the new DatabaseConnector version can be released soon.
=> Making tests if table exists on server case-insensitive.

DESCRIPTION, R/SklearnClassifierHelpers.R
@jreps , I made a faster version of listCartesian. This is used when enumerating the hyperparameter space for the models. For some of the deep learning models in deepPLP this was taking an annoyingly long time (even up to many minutes). So I rewrote the function for a 10x speedup.
Note I had to add shinydashboards to the DESCRIPTION to get the R check to pass. I assume that's related to your shiny app development.
=> Faster listCartesian

R/RunMultiplePlp.R
A very small change that moves the loading of PLP data (if it already exists) slightly to save loading it when analysis exist as well. Found it useful when running strategus multiple times.
All tests passed locally on ubuntu.
=> move loadPlpData in runMultiple to save loading until later

inst/sql/sql_server/PlpResultTables.sql
Aims to address #407 by updating the results data model
=> Change execution_date_time to varchar(100)

.github/workflows/R_CMD_check_Hades.yaml, DESCRIPTION, NEWS.md, R/SklearnToJson.R, README.md
Fixes #406 
The issue was that in `scikit-learn 1.3` they added a new feature to decision trees to deal with missing data. This broke our serialization of `scikit-learn` models to json. The reason this was not detected in our regular tests but in the weekly Hades tests is that there was inconsistency in how python environments were set up for testing. It was hardcoded in our regular test github actions to use `python 3.7`, which has gone out of support. This resulted in our tests using an older version of `scikit-learn` which didn't have this issue.
In this PR I've 
- Fixed the serialization of trees so they work both with `scikit-learn 1.3` and older versions.
- Simplified the actions so the setup of python env uses `configurePython` function for consistency
- Update ubuntu runner to use …
=> 406 hades weekly fail - hotfix

.github/workflows/R_CMD_check_Hades.yaml, R/HelperFunctions.R, man/configurePython.Rd
Hi @jreps ,
This is a fix for a python issue which was causing tests to fail. After this fix tests on windows and ubuntu should pass, while tests on macOS are still failing because of the vroom issue that's affecting many.
I've now set as a default python version 3.11 when creating a new conda environment using the `configurePython` function.
=> 413 python fix

R/PopulationSettings.R
@jreps 
When we create our `population` with `firstExposureOnly` set to `TRUE there is a very expensive [group_by](https://github.com/OHDSI/PatientLevelPrediction/blob/main/R/PopulationSettings.R#L297) operation done:
```R 
population <- population %>%
dplyr::arrange(.data$subjectId,.data$cohortStartDate) %>%
dplyr::group_by(.data$subjectId) %>%
dplyr::filter(dplyr::row_number(.data$subjectId)==1)
```
The amount of groups is equal to amount of subjects, so possibly millions. 
When there is only one observation per `subjectId` this is a no-op and can be skipped. 
In this PR I've added a condition:
```R
(nrow(population) > dplyr::n_distinct(population$subjectId))
```
If rows in population are more than amount of subjects (aka more observations than subjects), then and only then we do this …
=> only restict to first if many observations per subjectId

R/HelperFunctions.R
=> fix assignment operator in configurePython

R/PopulationSettings.R
- Minor speed improvements by moving filter operations before joins
- Fixed a bug where `creatingStudyPopulation` with an existing pop failed sometimes (I think when multiple outcome cohorts were present in `plpData$outcomes` and/or when each subject had multiple observations)
=> Study population improvements

R/RunPlp.R
=> skip population creation if exists

R/RunPlp.R, tests/testthat/test-population.R
Fixed my own mistake - didn't assign the population object correctly in the last PR. Added a unit tests that tests when we use an existing population in our code.
=> assign population if existing and added a test

R/ExternalValidatePlp.R
It was created multiple time (inside the nested for loop) and only closed when exiting the function. This resulted in multiple duplicate lines being logged in the file.
=> Fix logger for external validation

R/ExternalValidatePlp.R, tests/testthat/test-validation.R
Creates a separate design for each `restrictPlpDataSetting` in the list.
=> createValidationDesign accepts a list of restrictPlpDataSettings

R/ParamChecks.R, R/SklearnClassifier.R, R/SklearnClassifierHelpers.R, R/SklearnClassifierSettings.R, R/SklearnToJson.R, man/createFeatureEngineeringSettings.Rd, man/setAdaBoost.Rd, man/setDecisionTree.Rd, man/setRandomForest.Rd, man/setSVM.Rd, tests/testthat/test-sklearnClassifier.R, tests/testthat/test-sklearnClassifierHelpers.R, tests/testthat/test-sklearnClassifierSettings.R
=> fix sklearn deprecated value for adaboost
